apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lts3
  name: lts3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lts3
  template:
    metadata:
      labels:
        app: lts3
    spec:
      containers:
      - image: webpooh/lts3:2.1
        name: lts3
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/sites-enabled/default
          readOnly: true
          name: nginx-default
          subPath: default
      volumes:
      - name: nginx-default
        configMap:
          name: lts3-cm
          items:
            - key: default 
              path: default
